In [74]:
import pandas as pd
import matplotlib as plt

In [75]:
def eda (df):
    print('Número de filas:')
    display(df.shape[0])
    print('----------------------------------------------------------------------------------')
    print('Número de columnas:')
    display(df.shape[1])
    print('----------------------------------------------------------------------------------')
    print('Información dataframe:')
    display(df.info())
    print('----------------------------------------------------------------------------------')
    print('Nombre de las columnas:')
    display(df.columns)
    print('----------------------------------------------------------------------------------')
    columnas_num = df.select_dtypes(include='number')
    if not columnas_num.empty:
        print('Descripción datos numéricos:')
        display(columnas_num.describe().T)
    else:
        print('No hay datos de tipo numérico')
    print('----------------------------------------------------------------------------------')
    columnas_str = df.select_dtypes(include='object')
    if not columnas_str.empty:
        print('Descripción datos string:')
        display(columnas_str.describe().T)
    else:
        print('No hay datos de tipo string')
    print('----------------------------------------------------------------------------------')
    columnas_fecha = df.select_dtypes(include='datetime')
    if not columnas_fecha.empty:
        print('Descripción datos fechas:')
        display(columnas_fecha.describe().T)
    else:
        print('No hay datos de tipo fechas')
    print('----------------------------------------------------------------------------------')
    print('Cuantos datos únicos hay por columna:')
    display(df.nunique())
    print('----------------------------------------------------------------------------------')
    for col in df.columns:
        print(f'Datos unicos de la {col}:\n {df[col].value_counts()}\n')
    print('----------------------------------------------------------------------------------')
    print('Cuantos datos nulos hay:')
    display(df.isnull().sum())
    print('----------------------------------------------------------------------------------')
    porcentajes_nulos = df.isnull().mean() * 100
    cols_numericas = df.select_dtypes(include=['number']).columns
    cols_categoricas = df.select_dtypes(include=['object', 'category']).columns
    cols_fechas = df.select_dtypes(include=['datetime']).columns
    nulos_numericas = porcentajes_nulos[cols_numericas]
    nulos_categoricas = porcentajes_nulos[cols_categoricas]
    nulos_fechas = porcentajes_nulos[cols_fechas]
    if (porcentajes_nulos > 0).any():
        if (nulos_numericas > 0).any():
            print('Porcentajes de nulos en columnas numéricas:')
            print(nulos_numericas.sort_values(ascending=False))
        else:
            print('No hay nulos en columnas numéricas.')
            print('----------------------------------------------------------------------------------')
        if (nulos_categoricas > 0).any():
            print('\nPorcentajes de nulos en columnas categóricas:')
            print(nulos_categoricas.sort_values(ascending=False))
        else:
            print('No hay nulos en columnas categóricas.')
            print('----------------------------------------------------------------------------------')
        if (nulos_fechas > 0).any():
            print('\nPorcentajes de nulos en columnas de fechas:')
            print(nulos_fechas.sort_values(ascending=False))
        else:
            print('No hay nulos en columnas de fechas.')
    else:
        pass
    print('----------------------------------------------------------------------------------')
    cantid_duplicadas = df.duplicated().sum()
    print(f'Cantidad de duplicados: {cantid_duplicadas}')
    if cantid_duplicadas >0:
        print('Primeros duplicados:')
        display(df[df.duplicated()].head(3))
    else:
        print('No hay duplicados')
    print('------------------------------------------------------------------------------------')
    print('Columnas constantes (solo 1 valor único):')
    constantes = df.columns[df.nunique() <= 1]
    if len(constantes) > 0:
        print(f'{len(constantes)} columnas con 1 valor único:')
        display(constantes)
    else:
        print('No hay columnas constantes')
    print('------------------------------------------------------------------------------------')

In [76]:
df = pd.read_csv('mental_health_dataset.csv', index_col=False)
df

,age,gender,employment_status,work_environment,mental_health_history,seeks_treatment,stress_level,sleep_hours,physical_activity_days,depression_score,anxiety_score,social_support_score,productivity_score,mental_health_risk
0,56,Male,Employed,On-site,Yes,Yes,6,6.2,3,28,17,54,59.7,High
1,46,Female,Student,On-site,No,Yes,10,9.0,4,30,11,85,54.9,High
2,32,Female,Employed,On-site,Yes,No,7,7.7,2,24,7,62,61.3,Medium
3,60,Non-binary,Self-employed,On-site,No,No,4,4.5,4,6,0,95,97.0,Low
4,25,Female,Self-employed,On-site,Yes,Yes,3,5.4,0,24,12,70,69.0,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,34,Female,Employed,On-site,Yes,Yes,5,6.1,3,9,21,8,90.0,Medium
9996,47,Male,Employed,On-site,Yes,No,1,5.7,3,5,12,45,90.8,Medium
9997,56,Female,Employed,On-site,Yes,No,1,8.3,0,1,18,7,99.2,Medium
9998,24,Male,Employed,On-site,Yes,Yes,9,6.1,0,28,21,32,56.7,High
9999,44,Male,Unemployed,Remote,No,Yes,5,6.4,7,1,16,25,100.0,Medium

In [77]:
df1 = pd.read_excel('Mental health Depression disorder Data.xlsx', index_col=False)
df1

,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,AFG,1990,0.160560,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260
...,...,...,...,...,...,...,...,...,...,...
6463,Zimbabwe,ZWE,2013,0.155670,0.607993,0.117248,3.090168,0.766280,3.128192,1.515641
6464,Zimbabwe,ZWE,2014,0.155993,0.608610,0.118073,3.093964,0.768914,3.140290,1.515470
6465,Zimbabwe,ZWE,2015,0.156465,0.609363,0.119470,3.098687,0.771802,3.155710,1.514751
6466,Zimbabwe,ZWE,2016,0.157111,0.610234,0.121456,3.104294,0.772275,3.174134,1.513269
6467,Zimbabwe,ZWE,2017,0.157963,0.611242,0.124443,3.110926,0.772648,3.192789,1.510943

In [78]:
df1.drop('Code', axis=1, inplace=True)
df1.head(1)

,Entity,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,1990,0.16056,0.697779,0.101855,4.82883,1.677082,4.071831,0.672404

In [79]:
df2 = pd.read_csv('Mental Health Dataset.csv', index_col=False)
df2

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292359,7/27/2015 23:25,Male,United States,Business,Yes,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,Maybe,Not sure
292360,8/17/2015 9:38,Male,South Africa,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292361,8/25/2015 19:59,Male,United States,Business,No,Yes,No,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,No
292362,9/26/2015 1:07,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292363,2/1/2016 23:04,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes

In [80]:
def extraer_año(df, columna_fecha):
    """
    Extrae el año de una columna de tipo fecha+hora y reemplaza los valores en la misma columna.

    Parámetros:
    - df: DataFrame de pandas
    - columna_fecha: nombre de la columna (string) que contiene datos de fecha+hora

    Retorna:
    - El DataFrame con la columna modificada (solo el año)
    """
    df2['Timestamp'] = pd.to_datetime(df2['Timestamp'], errors='coerce')  # Convertir a datetime
    df2['Timestamp'] = df2['Timestamp'].dt.year  # Extraer el año
    return df2

In [81]:
extraer_año(df2, 'Timestamp')
df2.head(3)

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,2014,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,2014,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,2014,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [82]:
df2.rename(columns={'Timestamp': 'Year'}, inplace=True)
df2.head(1)

,Year,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,2014,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure

In [83]:
eda(df2)

Número de filas:

292364

----------------------------------------------------------------------------------
Número de columnas:

17

----------------------------------------------------------------------------------
Información dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292364 entries, 0 to 292363
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Year                     292364 non-null  int32
 1   Gender                   292364 non-null  object
 2   Country                  292364 non-null  object
 3   Occupation               292364 non-null  object
 4   self_employed            287162 non-null  object
 5   family_history           292364 non-null  object
 6   treatment                292364 non-null  object
 7   Days_Indoors             292364 non-null  object
 8   Growing_Stress           292364 non-null  object
 9   Changes_Habits           292364 non-null  object
 10  Mental_Health_History    292364 non-null  object
 11  Mood_Swings              292364 non-null  object
 12  Coping_Struggles         292364 non-null  object
 13  Work_Interest            292364 non-null  object
 14  Social_Weakness          292364 non-null  object
 15  mental_health_interview  292364 non-null  object
 16  care_options             292364 non-null  object
dtypes: int32(1), object(16)
memory usage: 36.8+ MB

None

----------------------------------------------------------------------------------
Nombre de las columnas:

Index(['Year', 'Gender', 'Country', 'Occupation', 'self_employed',
       'family_history', 'treatment', 'Days_Indoors', 'Growing_Stress',
       'Changes_Habits', 'Mental_Health_History', 'Mood_Swings',
       'Coping_Struggles', 'Work_Interest', 'Social_Weakness',
       'mental_health_interview', 'care_options'],
      dtype='object')

----------------------------------------------------------------------------------
Descripción datos numéricos:

         count         mean       std     min     25%     50%     75%     max
Year  292364.0  2014.052927  0.229769  2014.0  2014.0  2014.0  2014.0  2016.0

----------------------------------------------------------------------------------
Descripción datos string:

                          count unique            top    freq
Gender                   292364      2           Male  239850
Country                  292364     35  United States  171308
Occupation               292364      5      Housewife   66351
self_employed            287162      2             No  257994
family_history           292364      2             No  176832
treatment                292364      2            Yes  147606
Days_Indoors             292364      5      1-14 days   63548
Growing_Stress           292364      3          Maybe   99985
Changes_Habits           292364      3            Yes  109523
Mental_Health_History    292364      3             No  104018
Mood_Swings              292364      3         Medium  101064
Coping_Struggles         292364      2             No  154328
Work_Interest            292364      3             No  105843
Social_Weakness          292364      3          Maybe  103393
mental_health_interview  292364      3             No  232166
care_options             292364      3             No  118886

----------------------------------------------------------------------------------
No hay datos de tipo fechas
----------------------------------------------------------------------------------
Cuantos datos únicos hay por columna:

Year                        3
Gender                      2
Country                    35
Occupation                  5
self_employed               2
family_history              2
treatment                   2
Days_Indoors                5
Growing_Stress              3
Changes_Habits              3
Mental_Health_History       3
Mood_Swings                 3
Coping_Struggles            2
Work_Interest               3
Social_Weakness             3
mental_health_interview     3
care_options                3
dtype: int64

----------------------------------------------------------------------------------
Datos unicos de la Year:
 Year
2014    277280
2015     14694
2016       390
Name: count, dtype: int64

Datos unicos de la Gender:
 Gender
Male      239850
Female     52514
Name: count, dtype: int64

Datos unicos de la Country:
 Country
United States             171308
United Kingdom             51404
Canada                     18726
Australia                   6026
Netherlands                 5894
Ireland                     5548
Germany                     4680
Sweden                      2818
India                       2774
France                      2340
Brazil                      2340
New Zealand                 1994
South Africa                1994
Italy                       1560
Switzerland                 1560
Israel                      1560
Poland                       824
Belgium                      824
Russia                       780
Greece                       780
Denmark                      780
Singapore                    780
Portugal                     390
Costa Rica                   390
Nigeria                      390
Bosnia and Herzegovina       390
Finland                      390
Thailand                     390
Croatia                      390
Mexico                       390
Moldova                      390
Colombia                     390
Georgia                      390
Czech Republic               390
Philippines                  390
Name: count, dtype: int64

Datos unicos de la Occupation:
 Occupation
Housewife    66351
Student      61794
Corporate    61229
Others       52841
Business     50149
Name: count, dtype: int64

Datos unicos de la self_employed:
 self_employed
No     257994
Yes     29168
Name: count, dtype: int64

Datos unicos de la family_history:
 family_history
No     176832
Yes    115532
Name: count, dtype: int64

Datos unicos de la treatment:
 treatment
Yes    147606
No     144758
Name: count, dtype: int64

Datos unicos de la Days_Indoors:
 Days_Indoors
1-14 days             63548
31-60 days            60705
Go out Every day      58366
More than 2 months    55916
15-30 days            53829
Name: count, dtype: int64

Datos unicos de la Growing_Stress:
 Growing_Stress
Maybe    99985
Yes      99653
No       92726
Name: count, dtype: int64

Datos unicos de la Changes_Habits:
 Changes_Habits
Yes      109523
Maybe     95166
No        87675
Name: count, dtype: int64

Datos unicos de la Mental_Health_History:
 Mental_Health_History
No       104018
Maybe     95378
Yes       92968
Name: count, dtype: int64

Datos unicos de la Mood_Swings:
 Mood_Swings
Medium    101064
Low        99834
High       91466
Name: count, dtype: int64

Datos unicos de la Coping_Struggles:
 Coping_Struggles
No     154328
Yes    138036
Name: count, dtype: int64

Datos unicos de la Work_Interest:
 Work_Interest
No       105843
Maybe    101185
Yes       85336
Name: count, dtype: int64

Datos unicos de la Social_Weakness:
 Social_Weakness
Maybe    103393
No        97364
Yes       91607
Name: count, dtype: int64

Datos unicos de la mental_health_interview:
 mental_health_interview
No       232166
Maybe     51574
Yes        8624
Name: count, dtype: int64

Datos unicos de la care_options:
 care_options
No          118886
Yes          95712
Not sure     77766
Name: count, dtype: int64

----------------------------------------------------------------------------------
Cuantos datos nulos hay:

Year                          0
Gender                        0
Country                       0
Occupation                    0
self_employed              5202
family_history                0
treatment                     0
Days_Indoors                  0
Growing_Stress                0
Changes_Habits                0
Mental_Health_History         0
Mood_Swings                   0
Coping_Struggles              0
Work_Interest                 0
Social_Weakness               0
mental_health_interview       0
care_options                  0
dtype: int64

----------------------------------------------------------------------------------
No hay nulos en columnas numéricas.
----------------------------------------------------------------------------------

Porcentajes de nulos en columnas categóricas:
self_employed              1.779289
Gender                     0.000000
Country                    0.000000
Occupation                 0.000000
family_history             0.000000
treatment                  0.000000
Days_Indoors               0.000000
Growing_Stress             0.000000
Changes_Habits             0.000000
Mental_Health_History      0.000000
Mood_Swings                0.000000
Coping_Struggles           0.000000
Work_Interest              0.000000
Social_Weakness            0.000000
mental_health_interview    0.000000
care_options               0.000000
dtype: float64
No hay nulos en columnas de fechas.
----------------------------------------------------------------------------------
Cantidad de duplicados: 186718
Primeros duplicados:

,Year,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
9,2014,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
11,2014,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
12,2014,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No

------------------------------------------------------------------------------------
Columnas constantes (solo 1 valor único):
No hay columnas constantes
------------------------------------------------------------------------------------

In [84]:
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

In [85]:
def imputacion_nulos(df):
    # Imputación de columnas categóricas:
    columnas_categóricas_con_nulos = df[df.columns[df.isnull().any()]].select_dtypes(include = "O").columns
    for col in columnas_categóricas_con_nulos:
        nulos = df[col].isnull().sum()
        total = len(df)
        porcentaje_nulos = nulos / total

        if porcentaje_nulos > 0.20:
            # Si hay más del 20% de nulos; rellenar con "Desconocido"
            df[col] = df[col].fillna("Desconocido")
            print(f"{col} se va a imputar con Desconocido")
        else:
            # Menos del 20% de nulos
            valores = df[col].value_counts(dropna=True)
            if len(valores) >= 2:
                # Calcular diferencia porcentual entre los dos más frecuentes
                primero = valores.iloc[0]
                segundo = valores.iloc[1]
                diferencia = (primero - segundo) / total

                if diferencia > 0.20:
                    # Si la diferencia entre los dos más comunes > 20% → usar moda
                    moda = valores.idxmax() #es lo mismo que decirle la moda = df[col].mode[0]
                    df[col] = df[col].fillna(moda)
                    print(f"{col} se va a imputar con la moda")
                else:
                    # Si no → usar "Desconocido"
                    df[col] = df[col].fillna("Desconocido")
                    print(f"{col} se va a imputar con Desconocido")
            else:
                moda = valores.idxmax() #es lo mismo que decirle la moda = df[col].mode[0]
                df[col] = df[col].fillna(moda)
                print(f"{col} se va a imputar con la moda")

In [86]:
imputacion_nulos(df2)

self_employed se va a imputar con la moda

In [87]:
df2.isnull().sum()

Year                       0
Gender                     0
Country                    0
Occupation                 0
self_employed              0
family_history             0
treatment                  0
Days_Indoors               0
Growing_Stress             0
Changes_Habits             0
Mental_Health_History      0
Mood_Swings                0
Coping_Struggles           0
Work_Interest              0
Social_Weakness            0
mental_health_interview    0
care_options               0
dtype: int64

In [88]:
df2 = df2.drop_duplicates()
df2.duplicated().sum()

np.int64(0)

In [89]:
def limpieza(df):
    columnas_num = df.select_dtypes(include=['number']).columns
    for col in columnas_num:
        df[col] = df[col].astype(str)
        df[col] = df[col].str.replace('.', ',')
    df.columns = [col.replace('_', ' ').title() for col in df.columns]
    return df

In [90]:
limpieza(df2)
df2

C:\Users\AIDA\AppData\Local\Temp\ipykernel_11592\424931435.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str)
C:\Users\AIDA\AppData\Local\Temp\ipykernel_11592\424931435.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.replace('.', ',')

,Year,Gender,Country,Occupation,Self Employed,Family History,Treatment,Days Indoors,Growing Stress,Changes Habits,Mental Health History,Mood Swings,Coping Struggles,Work Interest,Social Weakness,Mental Health Interview,Care Options
0,2014,Female,United States,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,2014,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,2014,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,2014,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
5,2014,Female,Poland,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Not sure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292358,2015,Male,United States,Business,No,No,No,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,Maybe,Not sure
292359,2015,Male,United States,Business,Yes,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,Maybe,Not sure
292360,2015,Male,South Africa,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292361,2015,Male,United States,Business,No,Yes,No,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,No
292363,2016,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes

In [91]:
limpieza(df)
df

,Age,Gender,Employment Status,Work Environment,Mental Health History,Seeks Treatment,Stress Level,Sleep Hours,Physical Activity Days,Depression Score,Anxiety Score,Social Support Score,Productivity Score,Mental Health Risk
0,56,Male,Employed,On-site,Yes,Yes,6,"6,2",3,28,17,54,"59,7",High
1,46,Female,Student,On-site,No,Yes,10,"9,0",4,30,11,85,"54,9",High
2,32,Female,Employed,On-site,Yes,No,7,"7,7",2,24,7,62,"61,3",Medium
3,60,Non-binary,Self-employed,On-site,No,No,4,"4,5",4,6,0,95,"97,0",Low
4,25,Female,Self-employed,On-site,Yes,Yes,3,"5,4",0,24,12,70,"69,0",High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,34,Female,Employed,On-site,Yes,Yes,5,"6,1",3,9,21,8,"90,0",Medium
9996,47,Male,Employed,On-site,Yes,No,1,"5,7",3,5,12,45,"90,8",Medium
9997,56,Female,Employed,On-site,Yes,No,1,"8,3",0,1,18,7,"99,2",Medium
9998,24,Male,Employed,On-site,Yes,Yes,9,"6,1",0,28,21,32,"56,7",High
9999,44,Male,Unemployed,Remote,No,Yes,5,"6,4",7,1,16,25,"100,0",Medium

In [92]:
limpieza(df1)
df1

,Entity,Year,Schizophrenia (%),Bipolar Disorder (%),Eating Disorders (%),Anxiety Disorders (%),Drug Use Disorders (%),Depression (%),Alcohol Use Disorders (%)
0,Afghanistan,1990,"0,160559542157","0,697779384535","0,101854863459","4,82882970499999","1,67708194479","4,07183117706","0,672404086186"
1,Afghanistan,1991,"0,16031189863","0,697960594942","0,0993127900960999","4,82974037241","1,68474573106","4,07953093539999","0,671768123935"
2,Afghanistan,1992,"0,160134822429","0,698106968899","0,0966915892928","4,83110836569","1,69433394456999","4,08835824297","0,670644008146"
3,Afghanistan,1993,"0,160037391188","0,698256934369","0,0943356623795","4,83086358539","1,70532046528","4,09618989711999","0,669737960231"
4,Afghanistan,1994,"0,160022297338","0,69846911816","0,0924393209042","4,82942317312","1,71606858137","4,09958157816","0,669259592734"
...,...,...,...,...,...,...,...,...,...
6463,Zimbabwe,2013,"0,155669694963","0,607992596281","0,117247872942","3,09016849248999","0,766280163535","3,12819230242","1,51564091268"
6464,Zimbabwe,2014,"0,155992630517","0,608610399716","0,118072943481","3,09396377885","0,768914210872","3,14029031934999","1,51546979404"
6465,Zimbabwe,2015,"0,156465117257","0,609362667682","0,119470072236999","3,09868670226999","0,77180178363","3,15570998789","1,51475147475"
6466,Zimbabwe,2016,"0,15711079947","0,610234233138999","0,121456054977","3,10429408842","0,772274572808","3,17413371298","1,5132688524"
6467,Zimbabwe,2017,"0,157963235821","0,611242389594","0,124443427153","3,1109255999","0,772648270742","3,19278911933999","1,51094346583999"

In [93]:
estudio_probabilidades_enfermedad_mental = df

In [94]:
habitos_salud_mental = df2

In [95]:
estadisticas_trastornos_mentales = df1

In [96]:
paises_filtrados = [
    'Australia', 'Belgium', 'Bosnia and Herzegovina', 'Brazil', 'Canada',
    'Colombia', 'Costa Rica', 'Croatia', 'Czech Republic', 'Denmark',
    'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'India', 'Ireland',
    'Israel', 'Italy', 'Mexico', 'Moldova', 'Netherlands', 'New Zealand',
    'Nigeria', 'Philippines', 'Poland', 'Portugal', 'Russia', 'Singapore',
    'South Africa', 'Sweden', 'Switzerland', 'Thailand', 'United Kingdom',
    'United States']

df_filtrado = estadisticas_trastornos_mentales[estadisticas_trastornos_mentales['Entity'].isin(paises_filtrados)].copy()

estadisticas_trastornos_mentales = df_filtrado

In [97]:
continentes = {
    # Europa
    'Belgium': 'Europa',
    'Bosnia and Herzegovina': 'Europa',
    'Croatia': 'Europa',
    'Czech Republic': 'Europa',
    'Denmark': 'Europa',
    'Finland': 'Europa',
    'France': 'Europa',
    'Georgia': 'Europa',
    'Germany': 'Europa',
    'Greece': 'Europa',
    'Ireland': 'Europa',
    'Italy': 'Europa',
    'Moldova': 'Europa',
    'Netherlands': 'Europa',
    'Poland': 'Europa',
    'Portugal': 'Europa',
    'Russia': 'Europa',
    'Sweden': 'Europa',
    'Switzerland': 'Europa',
    'United Kingdom': 'Europa',

    # América
    'Brazil': 'América',
    'Canada': 'América',
    'Colombia': 'América',
    'Costa Rica': 'América',
    'Mexico': 'América',
    'United States': 'América',

    # Oceanía
    'Australia': 'Oceanía',
    'New Zealand': 'Oceanía',

    # África
    'Nigeria': 'África',
    'South Africa': 'África',

    # Asia
    'Philippines': 'Asia',
    'India': 'Asia',
    'Israel': 'Asia',
    'Singapore': 'Asia',
    'Thailand': 'Asia',
}

In [98]:
estadisticas_trastornos_mentales['Continent'] = estadisticas_trastornos_mentales['Entity'].map(continentes)

In [99]:
estadisticas_trastornos_mentales.head(3)

,Entity,Year,Schizophrenia (%),Bipolar Disorder (%),Eating Disorders (%),Anxiety Disorders (%),Drug Use Disorders (%),Depression (%),Alcohol Use Disorders (%),Continent
308,Australia,1990,"0,360488563758999","1,12913444698","0,700090525224","6,52529436951","2,13323614922","4,62118658828","1,35291016420999",Oceanía
309,Australia,1991,"0,36119568201","1,13264691281","0,704108748089","6,51996827821999","2,18589310599","4,67193287901","1,39299745608",Oceanía
310,Australia,1992,"0,361892513407","1,13593554244","0,708000817574","6,51366330752","2,2350804112","4,71541226158","1,43015792333",Oceanía

In [100]:
habitos_salud_mental['Continent'] = habitos_salud_mental['Country'].map(continentes)

C:\Users\AIDA\AppData\Local\Temp\ipykernel_11592\1551448268.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  habitos_salud_mental['Continent'] = habitos_salud_mental['Country'].map(continentes)

In [101]:
habitos_salud_mental.head(3)

,Year,Gender,Country,Occupation,Self Employed,Family History,Treatment,Days Indoors,Growing Stress,Changes Habits,Mental Health History,Mood Swings,Coping Struggles,Work Interest,Social Weakness,Mental Health Interview,Care Options,Continent
0,2014,Female,United States,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure,América
1,2014,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No,América
2,2014,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes,América

In [102]:
df_largo = estadisticas_trastornos_mentales.melt(
    id_vars=['Entity', 'Year', 'Continent'],
    var_name='Disorder',
    value_name='Percentage'
)

# Opcional: quitar el símbolo %
df_largo['Disorder'] = df_largo['Disorder'].str.replace('%', '').str.replace('(', '').str.replace(')', '')

In [103]:
df_largo

             Entity  Year Continent                Disorder         Percentage
0         Australia  1990   Oceanía          Schizophrenia   0,360488563758999
1         Australia  1991   Oceanía          Schizophrenia       0,36119568201
2         Australia  1992   Oceanía          Schizophrenia      0,361892513407
3         Australia  1993   Oceanía          Schizophrenia      0,362523972112
4         Australia  1994   Oceanía          Schizophrenia      0,363000615429
...             ...   ...       ...                     ...                ...
6855  United States  2013   América  Alcohol Use Disorders       2,00581427099
6856  United States  2014   América  Alcohol Use Disorders       2,01134506373
6857  United States  2015   América  Alcohol Use Disorders       2,01873831093
6858  United States  2016   América  Alcohol Use Disorders       2,02826285677
6859  United States  2017   América  Alcohol Use Disorders       2,04008689286

[6860 rows x 5 columns]

In [104]:
estadisticas_trastornos_mentales.rename(columns={'Entity': 'Country'}, inplace=True)

In [105]:
df_largo.rename(columns={'Entity': 'Country'}, inplace=True)

In [106]:
estudio_probabilidades_enfermedad_mental.to_csv('estudio probabilidades enfermedad mental.csv', index=False)

In [107]:
estadisticas_trastornos_mentales.to_csv('estadisticas trastornos mentales.csv', index=False)

In [108]:
habitos_salud_mental.to_csv('habitos salud mental.csv', index=False)

In [109]:
df_largo.to_csv('estadisticas trastornos mentales modificado.csv', index=False)